# Makefile by Kévin Le Torc'h

EXE_1 = Embux
COMPILER = g++

ifeq ($(OS),Windows_NT)     					# Windows OS
    detected_OS := Windows
else
    detected_OS := $(shell uname) 				# Unix Based OS
endif

ifeq ($(CC),cc)									# If CC set to "cc"				
	CC = $(COMPILER)							# Forced to "gcc"
endif
ifeq ($(CC),)									# If no c compiler set
	CC = $(COMPILER)							# Forced to "gcc"
endif

INCLUDES = -Iinclude					# include folders
CFLAGS = -g -Wall -Wextra -Os -std=c++17		# Compiler flags
LDFLAGS = -lm -ansi								# Libs for all systems

ifeq ($(detected_OS),Windows)
    LDFLAGS += -Llib
	EXTENSION = .exe
	DELETE_CMD = del
else
    LDFLAGS += -Llib
	EXTENSION =
	DELETE_CMD = rm
endif


SRC = $(wildcard src/*.c)
NOM = $(basename $(notdir $(SRC)))
OBJ = $(addprefix obj/,$(addsuffix .o, $(NOM)))

all: $(EXE_1)$(EXTENSION)									# Build all executables

rebuild: remake												# Clean and build all executables

remake: clean $(EXE_1)$(EXTENSION)							# Same as rebuild

$(EXE_1)$(EXTENSION): $(OBJ)
	$(CC) $(OBJ) $(LDFLAGS) -o $@

# Build all the .o files
obj/%.o: src/%.c
	$(CC) -c $< $(INCLUDES) -o $@ $(CFLAGS)
	
# Remove all files generated by compilation (executables included)
clean:
	$(DELETE_CMD) $(OBJ) $(EXE_1)$(EXTENSION) *.gch -f

# Remove all files generated by compilation (except executables)
clear:
	$(DELETE_CMD) $(OBJ) *.gch -f

run: $(EXE_1)$(EXTENSION)
	./$(EXE_1)$(EXTENSION)